# Load packages for PatchSeq analysis
library("RNAseqQC")
library("DESeq2")
library("patchSeqQC")
library("ensembldb")
library("plyr")
library("dplyr")
library("ggplot2")
library("pheatmap")
library("purrr")
library("tidyr")
library("tidyverse")
library("tibble")
library("magrittr")
library("knitr")
library("tximport")
library("vsn")
